default: &default
  docker:
    - image: circleci/node:8.9.1
install_and_build: &install_and_build
  - restore_cache:
      keys:
        - checkout-{{ .Branch }}-{{ .Revision }}
  - restore_cache:
      keys:
        - npm-cache-{{ checksum "package.json" }}
  - run:
      name: Install
      command: npm i
  - save_cache:
      key: npm-cache-{{ checksum "package.json" }}
      paths:
        - node_modules
  - run:
      name: Build
      command: npm run build
version: 2
jobs:
  checkout:
    <<: *default
    working_directory: ~/props-cms
    steps:
      - checkout
      - save_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/props-cms
  build_client:
    <<: *default
    working_directory: ~/props-cms/client
    steps:
      *install_and_build
  build_server:
    <<: *default
    working_directory: ~/props-cms/server
    steps:
      *install_and_build
  build_connector_common:
    <<: *default
    working_directory: ~/props-cms/connector/common
    steps:
      *install_and_build
  build_connector_react:
    <<: *default
    working_directory: ~/props-cms/connector/react
    steps:
      *install_and_build
workflows:
  version: 2
  build-all:
    jobs:
      - checkout
      - build_client:
          requires:
            - checkout
      - build_server:
          requires:
            - checkout
      - build_connector_common:
          requires:
            - checkout
      - build_connector_react:
          requires:
            - checkout