default: &default
  docker:
    - image: circleci/node:8.9.1
install_and_build: &install_and_build
  - run:
      name: Show directory
      command: ls
  - run:
      name: Show directory
      command: cd ../../ && ls
  - run:
      name: Show directory
      command: cd ../../../ && ls
  - run:
      name: Show directory
      command: cd ../../../../ && ls
  - restore_cache:
      keys:
        - npm-cache-{{ checksum "package.json" }}
  - run:
      name: Install
      command: npm i
  - save_cache:
      key: npm-cache-{{ checksum "package.json" }}
      paths:
        - node_modules
  - run:
      name: Build
      command: npm run build
version: 2
jobs:
  checkout:
    <<: *default
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: dir
          command: echo $PWD
      - run:
          name: Show directory
          command: ls
      - run:
          name: Show directory
          command: cd ../ && ls
      - run:
          name: Show directory
          command: cd ../../ && ls
  build_client:
    <<: *default
    working_directory: /tmp/build/client
    steps:
      *install_and_build
  build_server:
    <<: *default
    working_directory: /tmp/build/server
    steps:
      *install_and_build
  build_connector_common:
    <<: *default
    working_directory: /tmp/build/connector/client
    steps:
      *install_and_build
  build_connector_react:
    <<: *default
    working_directory: /tmp/build/connector/react
    steps:
      *install_and_build
workflows:
  version: 2
  build-all:
    jobs:
      - checkout
      - build_client:
          requires:
            - checkout
      - build_server:
          requires:
            - checkout
      - build_connector_common:
          requires:
            - checkout
      - build_connector_react:
          requires:
            - checkout