install_and_build: &install_with_cache
  - restore_cache:
      keys:
        - npm-cache-{{ checksum "package.json" }}
  - run:
      name: Install
      command: npm i
  - save_cache:
      key: npm-cache-{{ checksum "package.json" }}
      paths:
        - node_modules
  - run
      name: Build
      command: npm run build
version: 2
jobs:
  build_client:
    working_directory: ~/tmp/client
    steps:
      - cd client
      <<: *install_and_build
  build_server:
    working_directory: ~/tmp/server
    steps:
      - cd server
      <<: *install_and_build
  build_connector_common:
    working_directory: ~/tmp/connector/client
    steps:
      - cd connector/client
      <<: *install_and_build
  build_connector_react:
    working_directory: ~/tmp/connector/react
    steps:
      - cd connector/react
      <<: *install_and_build
workflows:
  version: 2
  build-all:
    jobs:
      - build_client
      - build_server
      - build_connector_common
      - build_connector_react